server:
  port: 9001
spring:
  application:
    name: custom-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000 #触发服务降级的时间，默认时1000ms
      circuitBreaker:
        errorThresholdPercentage: 50 #触发熔断比例阈值，默认值50%
        sleepWindowInMillisecconds: 100000 #熔断后休眠时长，默认5秒
        requestVolumeThreshold: 20 #熔断触发最小请求次数，默认值20
ribbon:
  ConnectTimeout: 1000 # 连接超时时长
  ReadTimeout: 2000 # 数据通信超时时长
  MaxAutoRetries: 0 # 当前服务器的重试次数
  MaxAutoRetriesNextServer: 0 # 重试多少次服务
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试
feign:
  hystrix:
    enabled: true # 开启feign的熔断功能
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/xml,application/json # 设置压缩的数据类型
      min-request-size: 2048 # 设置触发压缩的大小下限
    response:
      enabled: true # 开启响应压缩
logging:
  level:
    org.antry: debug

