server:
  port: 8080
spring:
  redis:
    database: 0
    connect-timeout: 3000
    sentinel:
      master: mymaster
      nodes: 192.168.200.135:26379,192.168.200.135:26380,192.168.200.135:26381
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000

