
package org.antry.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserServiceImpl", targetNamespace = "http://impl.service.antry.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showUser", targetNamespace = "http://impl.service.antry.org/", className = "org.antry.service.impl.ShowUser")
    @ResponseWrapper(localName = "showUserResponse", targetNamespace = "http://impl.service.antry.org/", className = "org.antry.service.impl.ShowUserResponse")
    @Action(input = "http://impl.service.antry.org/UserServiceImpl/showUserRequest", output = "http://impl.service.antry.org/UserServiceImpl/showUserResponse")
    public String showUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

}
