server:
  port: 22222
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11111/eureka
    register-with-eureka: true
    fetch-registry: true
  server:
    eviction-interval-timer-in-ms: 60000
    enable-self-preservation: true